[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"  # auto bundles your function
  external_node_modules = []

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
